-- MOVIMENTO_ESTOQUE Constraints
ALTER TABLE MOVIMENTO_ESTOQUE
    ADD CONSTRAINT XPKMOVIMENTO_ESTOQUE PRIMARY KEY (SEQ_MOVIMENTO_ESTOQUE);

ALTER TABLE MOVIMENTO_ESTOQUE
    ADD CONSTRAINT R_24 FOREIGN KEY (COD_TIPO_MOVIMENTO_ESTOQUE)
    REFERENCES TIPO_MOVIMENTO_ESTOQUE (COD_TIPO_MOVIMENTO_ESTOQUE);

ALTER TABLE MOVIMENTO_ESTOQUE
    ADD CONSTRAINT R_17 FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTO (COD_PRODUTO);

-- PRODUTO_COMPOSTO Constraints
ALTER TABLE PRODUTO_COMPOSTO
    ADD CONSTRAINT XPKPRODUTO_COMPOSTO PRIMARY KEY (COD_PRODUTO_RELACIONADO, COD_PRODUTO);

ALTER TABLE PRODUTO_COMPOSTO
    ADD CONSTRAINT R_16 FOREIGN KEY (COD_PRODUTO_RELACIONADO)
    REFERENCES PRODUTO (COD_PRODUTO);

ALTER TABLE PRODUTO_COMPOSTO
    ADD CONSTRAINT R_15 FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTO (COD_PRODUTO);

-- HISTORICO_PEDIDO Constraints
ALTER TABLE HISTORICO_PEDIDO
    ADD CONSTRAINT XPKHISTORICO_PEDIDO PRIMARY KEY (SEQ_HISTORICO_PEDIDO);

ALTER TABLE HISTORICO_PEDIDO
    ADD CONSTRAINT R_25 FOREIGN KEY (COD_VENDEDOR)
    REFERENCES VENDEDOR (COD_VENDEDOR);

ALTER TABLE HISTORICO_PEDIDO
    ADD CONSTRAINT R_19 FOREIGN KEY (COD_PEDIDO)
    REFERENCES PEDIDO (COD_PEDIDO);

ALTER TABLE HISTORICO_PEDIDO
    ADD CONSTRAINT R_9 FOREIGN KEY (COD_CLIENTE)
    REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE HISTORICO_PEDIDO
    ADD CONSTRAINT R_8 FOREIGN KEY (SEQ_ENDERECO_CLIENTE)
    REFERENCES ENDERECO_CLIENTE (SEQ_ENDERECO_CLIENTE);

-- ITEM_PEDIDO Constraints
ALTER TABLE ITEM_PEDIDO
    ADD CONSTRAINT XPKITEM_PEDIDO PRIMARY KEY (COD_PEDIDO, COD_ITEM_PEDIDO);

ALTER TABLE ITEM_PEDIDO
    ADD CONSTRAINT R_3 FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTO (COD_PRODUTO);

ALTER TABLE ITEM_PEDIDO
    ADD CONSTRAINT R_2 FOREIGN KEY (COD_PEDIDO)
    REFERENCES PEDIDO (COD_PEDIDO);

-- PEDIDO Constraints
ALTER TABLE PEDIDO
    ADD CONSTRAINT XPKPEDIDO PRIMARY KEY (COD_PEDIDO);

ALTER TABLE PEDIDO
    ADD CONSTRAINT R_14 FOREIGN KEY (COD_USUARIO)
    REFERENCES USUARIO (COD_USUARIO);

ALTER TABLE PEDIDO
    ADD CONSTRAINT R_12 FOREIGN KEY (COD_VENDEDOR)
    REFERENCES VENDEDOR (COD_VENDEDOR);

ALTER TABLE PEDIDO
    ADD CONSTRAINT R_7 FOREIGN KEY (COD_PEDIDO_RELACIONADO)
    REFERENCES PEDIDO (COD_PEDIDO);

ALTER TABLE PEDIDO
    ADD CONSTRAINT R_6 FOREIGN KEY (SEQ_ENDERECO_CLIENTE)
    REFERENCES ENDERECO_CLIENTE (SEQ_ENDERECO_CLIENTE);

ALTER TABLE PEDIDO
    ADD CONSTRAINT R_1 FOREIGN KEY (COD_CLIENTE)
    REFERENCES CLIENTE (COD_CLIENTE);

-- CLIENTE_VENDEDOR Constraints
ALTER TABLE CLIENTE_VENDEDOR
    ADD CONSTRAINT XPKCLIENTE_VENDEDOR PRIMARY KEY (COD_CLIENTE, COD_VENDEDOR, DAT_INICIO);

ALTER TABLE CLIENTE_VENDEDOR
    ADD CONSTRAINT R_11 FOREIGN KEY (COD_VENDEDOR)
    REFERENCES VENDEDOR (COD_VENDEDOR);

ALTER TABLE CLIENTE_VENDEDOR
    ADD CONSTRAINT R_10 FOREIGN KEY (COD_CLIENTE)
    REFERENCES CLIENTE (COD_CLIENTE);

-- ENDERECO_CLIENTE Constraints
ALTER TABLE ENDERECO_CLIENTE
    ADD CONSTRAINT XPKENDERECO_CLIENTE PRIMARY KEY (SEQ_ENDERECO_CLIENTE);

ALTER TABLE ENDERECO_CLIENTE
    ADD CONSTRAINT R_22 FOREIGN KEY (COD_CIDADE)
    REFERENCES CIDADE (COD_CIDADE);

ALTER TABLE ENDERECO_CLIENTE
    ADD CONSTRAINT R_5 FOREIGN KEY (COD_TIPO_ENDERECO)
    REFERENCES TIPO_ENDERECO (COD_TIPO_ENDERECO);

ALTER TABLE ENDERECO_CLIENTE
    ADD CONSTRAINT R_4 FOREIGN KEY (COD_CLIENTE)
    REFERENCES CLIENTE (COD_CLIENTE);

-- ESTOQUE_PRODUTO Constraints
ALTER TABLE ESTOQUE_PRODUTO
    ADD CONSTRAINT XPKESTOQUE_PRODUTO PRIMARY KEY (COD_PRODUTO, COD_ESTOQUE, DAT_ESTOQUE);

ALTER TABLE ESTOQUE_PRODUTO
    ADD CONSTRAINT R_20 FOREIGN KEY (COD_ESTOQUE)
    REFERENCES ESTOQUE (COD_ESTOQUE);

ALTER TABLE ESTOQUE_PRODUTO
    ADD CONSTRAINT R_18 FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTO (COD_PRODUTO);

-- CIDADE Constraints
ALTER TABLE CIDADE
    ADD CONSTRAINT XPKCIDADE PRIMARY KEY (COD_CIDADE);

ALTER TABLE CIDADE
    ADD CONSTRAINT R_21 FOREIGN KEY (COD_ESTADO)
    REFERENCES ESTADO (COD_ESTADO);

-- ESTADO Constraints
ALTER TABLE ESTADO
    ADD CONSTRAINT XPKESTADO PRIMARY KEY (COD_ESTADO);

ALTER TABLE ESTADO
    ADD CONSTRAINT R_23 FOREIGN KEY (COD_PAIS)
    REFERENCES PAIS (COD_PAIS);

-- PAIS Constraints
ALTER TABLE PAIS
    ADD CONSTRAINT XPKPAIS PRIMARY KEY (COD_PAIS);

-- TIPO_MOVIMENTO_ESTOQUE Constraints
ALTER TABLE TIPO_MOVIMENTO_ESTOQUE
    ADD CONSTRAINT XPKTIPO_MOVIMENTO_ESTOQUE PRIMARY KEY (COD_TIPO_MOVIMENTO_ESTOQUE);
