-- MOVIMENTO_ESTOQUE
DROP TABLE MOVIMENTO_ESTOQUE CASCADE CONSTRAINTS;

CREATE TABLE MOVIMENTO_ESTOQUE (
    SEQ_MOVIMENTO_ESTOQUE NUMBER(15) NOT NULL,
    COD_PRODUTO NUMBER(10) NULL,
    DAT_MOVIMENTO_ESTOQUE DATE NULL,
    QTD_MOVIMENTACAO_ESTOQUE INTEGER NULL,
    COD_TIPO_MOVIMENTO_ESTOQUE NUMBER(2) NULL
);

CREATE UNIQUE INDEX XPKMOVIMENTO_ESTOQUE ON MOVIMENTO_ESTOQUE (SEQ_MOVIMENTO_ESTOQUE ASC);
CREATE INDEX XIF1MOVIMENTO_ESTOQUE ON MOVIMENTO_ESTOQUE (COD_PRODUTO ASC);
CREATE INDEX XIF2MOVIMENTO_ESTOQUE ON MOVIMENTO_ESTOQUE (COD_TIPO_MOVIMENTO_ESTOQUE ASC);

-- PRODUTO_COMPOSTO
DROP TABLE PRODUTO_COMPOSTO CASCADE CONSTRAINTS;

CREATE TABLE PRODUTO_COMPOSTO (
    COD_PRODUTO_RELACIONADO NUMBER(10) NOT NULL,
    COD_PRODUTO NUMBER(10) NOT NULL,
    QTD_PRODUTO NUMBER(6) NULL,
    QTD_PRODUTO_RELACIONADO NUMBER(6) NULL,
    STA_ATIVO CHAR(1) NULL,
    DAT_CADASTRO DATE NULL,
    DAT_CANCELAMENTO DATE NULL
);

CREATE UNIQUE INDEX XPKPRODUTO_COMPOSTO ON PRODUTO_COMPOSTO (COD_PRODUTO_RELACIONADO ASC, COD_PRODUTO ASC);
CREATE INDEX XIF1PRODUTO_COMPOSTO ON PRODUTO_COMPOSTO (COD_PRODUTO ASC);
CREATE INDEX XIF2PRODUTO_COMPOSTO ON PRODUTO_COMPOSTO (COD_PRODUTO_RELACIONADO ASC);

-- HISTORICO_PEDIDO
DROP TABLE HISTORICO_PEDIDO CASCADE CONSTRAINTS;

CREATE TABLE HISTORICO_PEDIDO (
    SEQ_HISTORICO_PEDIDO INTEGER NOT NULL,
    COD_PEDIDO NUMBER(10) NOT NULL,
    COD_CLIENTE NUMBER(10) NULL,
    DAT_PEDIDO DATE NULL,
    DAT_CANCELAMENTO DATE NULL,
    DAT_ENTREGA DATE NULL,
    VAL_TOTAL_PEDIDO NUMBER(12, 2) NULL,
    VAL_DESCONTO NUMBER(12, 2) NULL,
    SEQ_ENDERECO_CLIENTE NUMBER(10) NULL,
    COD_VENDEDOR NUMBER(4) NULL
);

CREATE UNIQUE INDEX XPKHISTORICO_PEDIDO ON HISTORICO_PEDIDO (SEQ_HISTORICO_PEDIDO ASC);
CREATE INDEX XIF1HISTORICO_PEDIDO ON HISTORICO_PEDIDO (SEQ_ENDERECO_CLIENTE ASC);
CREATE INDEX XIF2HISTORICO_PEDIDO ON HISTORICO_PEDIDO (COD_CLIENTE ASC);
CREATE INDEX XIF4HISTORICO_PEDIDO ON HISTORICO_PEDIDO (COD_PEDIDO ASC);
CREATE INDEX XIF5HISTORICO_PEDIDO ON HISTORICO_PEDIDO (COD_VENDEDOR ASC);

-- ITEM_PEDIDO
DROP TABLE ITEM_PEDIDO CASCADE CONSTRAINTS;

CREATE TABLE ITEM_PEDIDO (
    COD_PEDIDO NUMBER(10) NOT NULL,
    COD_ITEM_PEDIDO INTEGER NOT NULL,
    COD_PRODUTO NUMBER(10) NULL,
    QTD_ITEM NUMBER(10) NULL,
    VAL_UNITARIO_ITEM NUMBER(12, 2) NULL,
    VAL_DESCONTO_ITEM NUMBER(12, 2) NULL
);

CREATE UNIQUE INDEX XPKITEM_PEDIDO ON ITEM_PEDIDO (COD_PEDIDO ASC, COD_ITEM_PEDIDO ASC);
CREATE INDEX XIF1ITEM_PEDIDO ON ITEM_PEDIDO (COD_PEDIDO ASC);
CREATE INDEX XIF2ITEM_PEDIDO ON ITEM_PEDIDO (COD_PRODUTO ASC);

-- PEDIDO
DROP TABLE PEDIDO CASCADE CONSTRAINTS;

CREATE TABLE PEDIDO (
    COD_PEDIDO NUMBER(10) NOT NULL,
    COD_PEDIDO_RELACIONADO NUMBER(10) NULL,
    COD_CLIENTE NUMBER(10) NULL,
    COD_USUARIO NUMBER(5) NULL,
    COD_VENDEDOR NUMBER(4) NULL,
    DAT_PEDIDO DATE NULL,
    DAT_CANCELAMENTO DATE NULL,
    DAT_ENTREGA DATE NULL,
    VAL_TOTAL_PEDIDO NUMBER(12, 2) NULL,
    VAL_DESCONTO NUMBER(12, 2) NULL,
    SEQ_ENDERECO_CLIENTE NUMBER(10) NULL,
    STATUS VARCHAR2(30) NULL
);

CREATE UNIQUE INDEX XPKPEDIDO ON PEDIDO (COD_PEDIDO ASC);
CREATE INDEX XIF1PEDIDO ON PEDIDO (COD_CLIENTE ASC);
CREATE INDEX XIF2PEDIDO ON PEDIDO (SEQ_ENDERECO_CLIENTE ASC);
CREATE INDEX XIF3PEDIDO ON PEDIDO (COD_PEDIDO_RELACIONADO ASC);
CREATE INDEX XIF4PEDIDO ON PEDIDO (COD_VENDEDOR ASC);
CREATE INDEX XIF5PEDIDO ON PEDIDO (COD_USUARIO ASC);

-- USUARIO
DROP TABLE USUARIO CASCADE CONSTRAINTS;

CREATE TABLE USUARIO (
    COD_USUARIO NUMBER(5) NOT NULL,
    NOM_USUARIO VARCHAR2(50) NULL,
    STA_ATIVO CHAR(1) NULL
);

CREATE UNIQUE INDEX XPKUSUARIO ON USUARIO (COD_USUARIO ASC);

-- CLIENTE_VENDEDOR
DROP TABLE CLIENTE_VENDEDOR CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE_VENDEDOR (
    COD_CLIENTE NUMBER(10) NOT NULL,
    COD_VENDEDOR NUMBER(4) NOT NULL,
    DAT_INICIO DATE NOT NULL,
    DAT_TERMINO DATE NULL
);

CREATE UNIQUE INDEX XPKCLIENTE_VENDEDOR ON CLIENTE_VENDEDOR (COD_CLIENTE ASC, COD_VENDEDOR ASC, DAT_INICIO ASC);
CREATE INDEX XIF1CLIENTE_VENDEDOR ON CLIENTE_VENDEDOR (COD_CLIENTE ASC);
CREATE INDEX XIF2CLIENTE_VENDEDOR ON CLIENTE_VENDEDOR (COD_VENDEDOR ASC);

-- VENDEDOR
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;

CREATE TABLE VENDEDOR (
    COD_VENDEDOR NUMBER(4) NOT NULL,
    NOM_VENDEDOR VARCHAR2(50) NULL,
    STA_ATIVO CHAR(1) NULL
);

CREATE UNIQUE INDEX XPKVENDEDOR ON VENDEDOR (COD_VENDEDOR ASC);

-- ENDERECO_CLIENTE
DROP TABLE ENDERECO_CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE ENDERECO_CLIENTE (
    SEQ_ENDERECO_CLIENTE NUMBER(10) NOT NULL,
    COD_TIPO_ENDERECO NUMBER(2) NULL,
    COD_CLIENTE NUMBER(10) NULL,
    DES_ENDERECO VARCHAR2(80) NULL,
    NUM_ENDERECO VARCHAR2(10) NULL,
    DES_COMPLEMENTO VARCHAR2(20) NULL,
    NUM_CEP NUMBER(9) NULL,
    DES_BAIRRO VARCHAR2(50) NULL,
    COD_CIDADE NUMBER(6) NULL,
    STA_ATIVO CHAR(1) NULL,
    DAT_CADASTRO DATE NULL,
    DAT_CANCELAMENTO VARCHAR2(20) NULL
);

CREATE UNIQUE INDEX XPKENDERECO_CLIENTE ON ENDERECO_CLIENTE (SEQ_ENDERECO_CLIENTE ASC);
CREATE INDEX XIF1ENDERECO_CLIENTE ON ENDERECO_CLIENTE (COD_CLIENTE ASC);
CREATE INDEX XIF2ENDERECO_CLIENTE ON ENDERECO_CLIENTE (COD_TIPO_ENDERECO ASC);
CREATE INDEX XIF3ENDERECO_CLIENTE ON ENDERECO_CLIENTE (COD_CIDADE ASC);

-- TIPO_ENDERECO
DROP TABLE TIPO_ENDERECO CASCADE CONSTRAINTS;

CREATE TABLE TIPO_ENDERECO (
    COD_TIPO_ENDERECO NUMBER(2) NOT NULL,
    DES_TIPO_ENDERECO VARCHAR2(50) NULL
);

CREATE UNIQUE INDEX XPKTIPO_ENDERECO ON TIPO_ENDERECO (COD_TIPO_ENDERECO ASC);

-- ESTOQUE_PRODUTO
DROP TABLE ESTOQUE_PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE ESTOQUE_PRODUTO (
    COD_PRODUTO NUMBER(10) NOT NULL,
    COD_ESTOQUE NUMBER(4) NOT NULL,
    DAT_ESTOQUE DATE NOT NULL,
    QTD_PRODUTO NUMBER(10) NULL
);

CREATE UNIQUE INDEX XPKESTOQUE_PRODUTO ON ESTOQUE_PRODUTO (COD_PRODUTO ASC, COD_ESTOQUE ASC, DAT_ESTOQUE ASC);
CREATE INDEX XIF1ESTOQUE_PRODUTO ON ESTOQUE_PRODUTO (COD_PRODUTO ASC);
CREATE INDEX XIF2ESTOQUE_PRODUTO ON ESTOQUE_PRODUTO (COD_ESTOQUE ASC);

-- PRODUTO
DROP TABLE PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE PRODUTO (
    COD_PRODUTO NUMBER(10) NOT NULL,
    NOM_PRODUTO VARCHAR2(20) NULL,
    COD_BARRA VARCHAR2(20) NULL,
    STA_ATIVO VARCHAR2(20) NULL,
    DAT_CADASTRO DATE NULL,
    DAT_CANCELAMENTO DATE NULL
);

CREATE UNIQUE INDEX XPKPRODUTO ON PRODUTO (COD_PRODUTO ASC);

-- CLIENTE
DROP TABLE CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
    COD_CLIENTE NUMBER(10) NOT NULL,
    NOM_CLIENTE VARCHAR2(50) NULL,
    DES_RAZAO_SOCIAL VARCHAR2(80) NULL,
    TIP_PESSOA CHAR(1) NULL,
    NUM_CPF_CNPJ NUMBER(15) NULL,
    DAT_CADASTRO DATE NULL,
    DAT_CANCELAMENTO DATE NULL,
    STA_ATIVO CHAR(1) NULL
);

CREATE UNIQUE INDEX XPKCLIENTE ON CLIENTE (COD_CLIENTE ASC);

-- ESTOQUE
DROP TABLE ESTOQUE CASCADE CONSTRAINTS;

CREATE TABLE ESTOQUE (
    COD_ESTOQUE NUMBER(4) NOT NULL,
    NOM_ESTOQUE VARCHAR2(50) NULL
);

CREATE UNIQUE INDEX XPKESTOQUE ON ESTOQUE (COD_ESTOQUE ASC);

-- CIDADE
DROP TABLE CIDADE CASCADE CONSTRAINTS;

CREATE TABLE CIDADE (
    COD_CIDADE NUMBER(6) NOT NULL,
    NOM_CIDADE VARCHAR2(25) NULL,
    COD_ESTADO CHAR(3) NULL
);

CREATE UNIQUE INDEX XPKCIDADE ON CIDADE (COD_CIDADE ASC);
CREATE INDEX XIF1CIDADE ON CIDADE (COD_ESTADO ASC);

-- ESTADO
DROP TABLE ESTADO CASCADE CONSTRAINTS;

CREATE TABLE ESTADO (
    COD_ESTADO CHAR(3) NOT NULL,
    NOM_ESTADO VARCHAR2(50) NULL,
    COD_PAIS NUMBER(3) NULL
);

CREATE UNIQUE INDEX XPKESTADO ON ESTADO (COD_ESTADO ASC);
CREATE INDEX XIF1ESTADO ON ESTADO (COD_PAIS ASC);

-- PAIS
DROP TABLE PAIS CASCADE CONSTRAINTS;

CREATE TABLE PAIS (
    COD_PAIS NUMBER(3) NOT NULL,
    NOM_PAIS VARCHAR2(50) NULL
);

CREATE UNIQUE INDEX XPKPAIS ON PAIS (COD_PAIS ASC);

-- TIPO_MOVIMENTO_ESTOQUE
DROP TABLE TIPO_MOVIMENTO_ESTOQUE CASCADE CONSTRAINTS;

CREATE TABLE TIPO_MOVIMENTO_ESTOQUE (
    COD_TIPO_MOVIMENTO_ESTOQUE NUMBER(2) NOT NULL,
    DES_TIPO_MOVIMENTO_ESTOQUE VARCHAR2(50) NULL,
    STA_SAIDA_ENTRADA CHAR(1) NULL
);

CREATE UNIQUE INDEX XPKTIPO_MOVIMENTO_ESTOQUE ON TIPO_MOVIMENTO_ESTOQUE (COD_TIPO_MOVIMENTO_ESTOQUE ASC);
